input("enter two numbers to perform all arithmatic operations on that")
a = input("first number :")
b = input("second number :")
print("a+b=",int(a)+int(b))
print("a-b=",int(a)-int(b))
print("a*b=",int(a)*int(b))
print("a/b=",int(a)/int(b))